#!/bin/bash
set -e
# does this even do anything lmfao
SOURCE_DIR="./_english files (UTF-16)"
PORTAL_RESOURCE="~/.local/share/Steam/steamapps/common/Portal/portal/resource"
PORTAL2_RESOURCE="~/.local/share/Steam/steamapps/common/Portal 2/portal2/resource"
CAPTIONCOMPILER="~/.local/share/Steam/steamapps/common/Portal/bin/captioncompiler"
BACKUP_DIR="${PORTAL_RESOURCE}/backup"
mkdir -p "$BACKUP_DIR"
cp "${PORTAL_RESOURCE}/subtitles_english.txt" "$BACKUP_DIR/"
cp "${PORTAL_RESOURCE}/subtitles_english.dat" "$BACKUP_DIR/"
cp "${PORTAL_RESOURCE}/valve_english.txt" "$BACKUP_DIR/"
cp "${PORTAL_RESOURCE}/valve_english.dat" "$BACKUP_DIR/"
cp "${PORTAL_RESOURCE}/basemodui_english.txt" "$BACKUP_DIR/"
cp "${PORTAL_RESOURCE}/basemodui_english.dat" "$BACKUP_DIR/"
cp "${SOURCE_DIR}/subtitles_english.txt" "${PORTAL_RESOURCE}/"
cp "${SOURCE_DIR}/valve_english.txt" "${PORTAL_RESOURCE}/"
cp "${SOURCE_DIR}/basemodui_english.txt" "${PORTAL_RESOURCE}/"
"$CAPTIONCOMPILER" "${PORTAL_RESOURCE}/subtitles_english.txt" -game "${PORTAL_RESOURCE%/resource}/portal"
"$CAPTIONCOMPILER" "${PORTAL_RESOURCE}/valve_english.txt" -game "${PORTAL_RESOURCE%/resource}/portal"
"$CAPTIONCOMPILER" "${PORTAL_RESOURCE}/basemodui_english.txt" -game "${PORTAL_RESOURCE%/resource}/portal"
cp "${PORTAL_RESOURCE}/subtitles_english.txt" "${PORTAL2_RESOURCE}/"
cp "${PORTAL_RESOURCE}/subtitles_english.dat" "${PORTAL2_RESOURCE}/"
cp "${PORTAL_RESOURCE}/valve_english.txt" "${PORTAL2_RESOURCE}/"
cp "${PORTAL_RESOURCE}/valve_english.dat" "${PORTAL2_RESOURCE}/"
cp "${PORTAL_RESOURCE}/basemodui_english.txt" "${PORTAL2_RESOURCE}/"
cp "${PORTAL_RESOURCE}/basemodui_english.dat" "${PORTAL2_RESOURCE}/"
rm "${PORTAL_RESOURCE}/subtitles_english.txt"
rm "${PORTAL_RESOURCE}/subtitles_english.dat"
rm "${PORTAL_RESOURCE}/valve_english.txt"
rm "${PORTAL_RESOURCE}/valve_english.dat"
rm "${PORTAL_RESOURCE}/basemodui_english.txt"
rm "${PORTAL_RESOURCE}/basemodui_english.dat"
echo "done."
